feat(#1132): added chatControlPane F.C and sccs for it
kimbu-chat/web pull request #1169
Opened 2022-08-07 10:11 UTC by yanVojak

2022-08-07 11:20 UTC, remotenode requested changes

2022-08-07 11:20 UTC, remotenode commented on public/translation/ru.json
> +    "add-new-contact": "Добавить Новый Контак"
typo

2022-08-07 11:20 UTC, remotenode commented on src/components/chat-list/chat-control-panel/chat-control-panel.tsx
> +            onClick={() => closePanelAndOpenModal(onCreateGroupChat)}
button is re-rendered when the props change

2022-08-08 11:01 UTC, remotenode approved these changes

2022-08-08 11:10 UTC, skstef approved these changes

2022-08-08 12:39 UTC, merged